# a short string to identify the bridge
Identifier = "BTC2ETH"

# modgodb database connection config (server only)
[MongoDB]
DBURL = "localhost:27017"
DBName = "databasename"
UserName = "username"
Password = "password"

# bridge API service (server only)
[APIServer]
Port = 11556
AllowedOrigins = []

# oracle config (oracle only)
[Oracle]
# post swap register RPC requests to this server
ServerAPIAddress = "http://127.0.0.1:11556/rpc"

# customize fees in building btc transaction (server only)
[BtcExtra]
MinRelayFee   = 400
RelayFeePerKb = 2000
UtxoAggregateMinCount = 10
UtxoAggregateMinValue = 100000

# source token config
[SrcToken]
BlockChain = "Bitcoin"
NetID = "TestNet3"
ID = "BTC"
Name = "Bitcoin Coin"
Symbol = "BTC"
Decimals = 8
Description = "Bitcoin Coin"
ContractAddress = ""
DcrmAddress = "mfwPnCuht2b4Lvb5XTds4Rvzy3jZ2ZWrBL"
Confirmations = 0 # suggest >= 6 for Mainnet
MaximumSwap = 1000.0
MinimumSwap = 0.00001
SwapFeeRate = 0.001
InitialHeight = 0
MinTimeToRetry = 0 # unit seconds, suggest >= 3600 for Mainnet

# source blockchain gateway config
[SrcGateway]
APIAddress = ["http://47.107.50.83:3002"]

# dest token config
[DestToken]
BlockChain = "Ethereum"
NetID = "Rinkeby"
ID = "mBTC"
Name = "SMPC Bitcoin"
Symbol = "mBTC"
Decimals = 8
Description = "cross chain bridge BTC with mBTC"
ContractAddress = "0x61b8c4d6d28d5f7edadbea5456db3b4f7f836b64"
DcrmAddress = "0xbF0A46d3700E23a98F38079cE217742c92Bb66bC"
Confirmations = 0 # suggest >= 33 for Mainnet
MaximumSwap = 100.0
MinimumSwap = 0.00001
SwapFeeRate = 0.001
InitialHeight = 0
MinTimeToRetry = 0 # unit seconds, suggest >= 420 for Mainnet

# dest blockchain gateway config
[DestGateway]
APIAddress = ["http://5.189.139.168:8018"]

# DCRM config
[Dcrm]
# server dcrm user (initiator of dcrm sign)
ServerAccount = "0x00c37841378920E2BA5151a5d1E074Cf367586c4"

# dcrm group ID
GroupID = "74245ef03937fa75b979bdaa6a5952a93f53e021e0832fca4c2ad8952572c9b70f49e291de7e024b0f7fc54ec5875210db2ac775dba44448b3972b75af074d17"

# dcrm account public key
Pubkey = "045c8648793e4867af465691685000ae841dccab0b011283139d2eae454b569d5789f01632e13a75a5aad8480140e895dd671cae3639f935750bea7ae4b5a2512e"

# dcrm sub groups for signing (server only)
SignGroups = [
	"38a93f457c793ac3ee242b2c050a403774738e6558cfaa620fe5577bb15a28f63c39adcc0778497e5009a9ee776a0778ffcad4e95827e69efa21b893b8a78793",
	"bb1dfe1ec046cc3a3b88408ae03976aabffe459b40e5def09e76f5d4c7a917133241da9da7fc05e3e172fab54ce3129a9a492d52a5a09494d0b9c1e608f661bf"
]

# dcrm threshold (NeededOracles=2,TotalOracles=3 represent '2/3' threshold)
NeededOracles = 2
TotalOracles = 3

# dcrm mode (0:managed 1:private)
Mode = 0

# dcrm user keystore and password file (suggest using absolute path)
KeystoreFile = "/home/xxx/accounts/keystore1"
PasswordFile = "/home/xxx/accounts/password1"

# dcrm backend node (gdcrm node RPC address)
RPCAddress = "http://127.0.0.1:2922"
